### ISSUE TITLE
noob question: how do I get the translation in to a variable I can use elsewhere in code?

### ISSUE THREAD

**Issue by webmagnets** [ayanonagon/Polyglot#12] opened 2015-01-02 19:02 UTC
I am using this sample code:

		let translator = Polyglot(clientId: "8bacb905-c59b-4363-bbf5-89ef2c32c26e", clientSecret: "g82QvinzO7GhmP7qJQpfxTMXzClSGX3yiPcsedFDXYQ=")
		translator.fromLanguage = Language.ChineseSimplified
		translator.toLanguage = Language.English // English. This is the default.
		let wordString = "亚多尼洗德"
		translator.translate(wordString) { translation in
			println("\"\(wordString)\" means \"\(translation)\"")
		}

I want to show the translation in a tooltip and/or save it in a database. How can I get the string out of there and use it somewhere?

**Comment by ayanonagon** [comment] 2015-01-03 03:27
Where the `println` is currently is inside of the asynchronous callback, so you can’t do something like `let translation = translator.translate(wordString) { ...` but you should be able to use the `translation` variable like any other variable. Pass it into a function, set it to the text of the tool tip, etc.

You can see the [example project](https://github.com/ayanonagon/Polyglot/blob/master/PolyglotSample/ViewController.swift) or [one of my projects](https://github.com/ayanonagon/Spreken/blob/master/Spreken/TweetsViewController.swift#L138) that uses Polyglot.

Let me know if you have any other questions. :+1:

**Comment by ayanonagon** [comment] 2015-01-03 03:28
P.S. You might want to change your client secret on Microsoft’s site if the one in the issue is your real secret.

**Comment by webmagnets** [comment] 2015-01-03 16:28
Thanks for your help.

Here is what I tried:

```
override func viewDidLoad()
{
        super.viewDidLoad()
        self.translator = Polyglot(clientId: "MYid", clientSecret: "MYsecret")
        self.translator!.fromLanguage = Language.ChineseSimplified
        self.translator!.toLanguage = Language.English
        let wordString = w.simplified
        self.translator!.translate(wordString)
    { translation in
        println("\"\(wordString)\" means \"\(translation)\"") //this prints correctly
        toolTipContent = translation
    }
println("\(toolTipContent)") //this prints a blank line
}
```

**Comment by ayanonagon** [comment] 2015-01-03 16:51
That’s because `println("\(toolTipContent)")` gets called before `println("\"\(wordString)\" means \"\(translation)\"")`. (It must be the case in the order in which the lines are printed out in your console?) Everything inside of `{ translation in ... } happens asynchronously once `Polyglot` gets the translation which takes longer because it talks to the Microsoft Translator API via a network request. On the other hand, `println("\(toolTipContent)")` gets executed immediately after the translation begins to happen (not necessarily finished the translation at this point).

**Comment by ayanonagon** [comment] 2015-01-17 02:55
I’m going to close this, but let me know if you have any questions. :+1:

**Closed by ayanonagon** 2015-01-17 02:55 UTC
